/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/foods/frog.glb 
*/

import { useGLTF } from '@react-three/drei'

export default function Frog(props) {
    const { nodes, materials } = useGLTF('./models/foods/frog.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Frog_01_Cube029_1.geometry} material={materials['4CAF50']} />
            <mesh geometry={nodes.Frog_01_Cube029_1_1.geometry} material={materials['1A1A1A']} />
            <mesh geometry={nodes.Frog_01_Cube029_1_2.geometry} material={materials.FF9800} />
            <mesh geometry={nodes.Frog_01_Cube029_1_3.geometry} material={materials.F44336} />
        </group>
    )
}

useGLTF.preload('./models/foods/frog.glb')
