/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/foods/mice.glb 
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("./models/foods/mice.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.group1226118074.geometry}
				material={materials.mat16}
			/>
			<mesh
				geometry={nodes.group1415488189.geometry}
				material={materials.mat23}
			/>
			<mesh
				geometry={nodes.group501500655.geometry}
				material={materials.mat23}
			/>
			<mesh
				geometry={nodes.group1930673237.geometry}
				material={materials.mat7}
			/>
			<mesh
				geometry={nodes.group366457425.geometry}
				material={materials.mat6}
			/>
			<mesh
				geometry={nodes.mesh1244576720.geometry}
				material={materials.mat16}
			/>
			<mesh
				geometry={nodes.mesh1244576720_1.geometry}
				material={materials.mat6}
			/>
			<mesh
				geometry={nodes.mesh1190368398.geometry}
				material={materials.mat6}
			/>
			<mesh
				geometry={nodes.mesh1190368398_1.geometry}
				material={materials.mat16}
			/>
		</group>
	);
}

useGLTF.preload("./models/foods/mice.glb");
